server:
  port: 9097

spring:
  profiles:
    active: local
  application:
    name: deliveryUpdate
#  datasource:
#    #db name: foodcataloguedb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      # if there is update on data, it will update existing tables, not to create a new one
#      ddl-auto: update
#    show-sql: true
#    #    Convert based language to my SQL based query
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
